# Generated by Django 4.0.4 on 2022-07-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwash_yn', models.BooleanField(default=False)),
                ('handcream_yn', models.BooleanField(default=False)),
                ('sofrner_yn', models.BooleanField(default=False)),
                ('perfume_yn', models.BooleanField(default=False)),
                ('shampoo_yn', models.BooleanField(default=False)),
                ('rinse_yn', models.BooleanField(default=False)),
                ('bodywash_yn', models.BooleanField(default=False)),
                ('candle_yn', models.BooleanField(default=False)),
                ('room_yn', models.BooleanField(default=False)),
                ('diffuser_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='subSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=6)),
                ('subSelect_id', models.IntegerField()),
                ('diffuser_name', models.CharField(default='', max_length=100)),
                ('handwash_name', models.CharField(default='', max_length=100)),
                ('handcream_name', models.CharField(default='', max_length=100)),
                ('sofrner_name', models.CharField(default='', max_length=100)),
                ('perfume_name', models.CharField(default='', max_length=100)),
                ('shampoo_name', models.CharField(default='', max_length=100)),
                ('rinse_name', models.CharField(default='', max_length=100)),
                ('bodywash_name', models.CharField(default='', max_length=100)),
                ('candle_name', models.CharField(default='', max_length=100)),
                ('room_name', models.CharField(default='', max_length=100)),
                ('bodymist_name', models.CharField(default='', max_length=100)),
                ('bodylotion_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
