# Generated by Django 4.0.6 on 2022-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('pay_price', models.IntegerField(max_length=100)),
                ('pay_date', models.DateField()),
                ('pay_method', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
