# Generated by Django 4.0.4 on 2022-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sbti',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_date',
            field=models.DateField(null=True),
        ),
    ]
